In [2]:
import numpy as np
a=np.arange(0,10,2)
print(a)

[0 2 4 6 8]


In [3]:
b=np.arange(0,40,3)
print(b)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39]


In [8]:
a=np.linspace(1,5,4)
print(a)

[1.         2.33333333 3.66666667 5.        ]


In [14]:
arr=np.linspace(1,30,4)
arr

array([ 1.        , 10.66666667, 20.33333333, 30.        ])

In [22]:
arr=np.logspace(1,4,2)
arr

array([   10., 10000.])

In [23]:
aee=np.zeros(10)
aee

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
aee=np.zeros([3,5],dtype=np.int64)
aee

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

In [32]:
arr=np.zeros([2,2,3])
print(arr)
print(arr.shape)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
(2, 2, 3)


In [33]:
arr=np.ones([2,3],dtype=np.int64)
print(arr)

[[1 1 1]
 [1 1 1]]


In [37]:
arr=np.full(10,3)
arr

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [38]:
arr=np.full([3,4],10,dtype=np.int64)
arr

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]], dtype=int64)

In [46]:
emp=np.empty([4,3])
print(emp)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
