In [12]:
# array---->reshapping
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
reshaped=arr.reshape(4,2)
print(reshaped)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [10]:
resh=reshaped.reshape(2,4)
resh

array([[100,   2,   3,   4],
       [  5,   6,   7,   8]])

In [11]:
# ravel---->convert into 1D array
revel=resh.ravel()
revel

array([100,   2,   3,   4,   5,   6,   7,   8])

In [5]:
revel[0]=100
print(revel)
print(resh)

[100   2   3   4   5   6   7   8]
[[100   2   3   4]
 [  5   6   7   8]]


In [6]:
# flatten-->to 1D array
# --->return a copy of the array

flat=resh.flatten()
flat

array([100,   2,   3,   4,   5,   6,   7,   8])

In [7]:
flat[0]=1


In [8]:
flat

array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
resh

array([[100,   2,   3,   4],
       [  5,   6,   7,   8]])

ARITHMETIC OPERATORS ON ARRAYS

In [13]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [14]:
print(a+b)

[ 6  8 10 12]


In [16]:
print(a-b)
print(b-a)

[-4 -4 -4 -4]
[4 4 4 4]


In [17]:
print(a/b)

[0.2        0.33333333 0.42857143 0.5       ]


In [19]:
print(a*b)
print(a//b)

[ 5 12 21 32]
[0 0 0 0]


In [21]:
print(a%b)
print(a**b)

[1 2 3 4]
[    1    64  2187 65536]
