In [1]:
import numpy as np
a=np.array([1,2,3])
print(type(a))
print(a.ndim)

<class 'numpy.ndarray'>
1


In [15]:
b=np.array([[[[1,2,3],[1,3,2],[5,3,5]]]])
print(b.ndim)

4


In [4]:
import numpy as np
np.array([1,2,3,4])


array([1, 2, 3, 4])

In [5]:
arr=np.array([1,22,3,4])
print(arr.ndim)

1


In [6]:
arr=np.array(20)
print(arr.ndim)

0


In [20]:
arr=np.array([[[[1,2,3,4],[2,3,4,5],[1,2,3,4]]]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[[[1 2 3 4]
   [2 3 4 5]
   [1 2 3 4]]]]
4
(1, 1, 3, 4)


In [22]:
range=np.arange(1,30,3)
print(range)

[ 1  4  7 10 13 16 19 22 25 28]
