In [4]:
import numpy as np
print(np.__version__)

1.26.4


In [25]:
arr=np.array([10.1,12,13,15],dtype=int)
print(arr)
print([1,2,3])
print('shape of id:',arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

[10 12 13 15]
[1, 2, 3]
shape of id: (4,)
4
1
int32


In [28]:
arr2d=np.array([[1,2,3,4],[5,6,7,8]],dtype=float)
print(arr2d)
print(type(arr2d))
print('shape of 2d:',arr2d.shape)
print(arr2d.size)
print(arr2d.ndim)
print(arr2d.dtype)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
<class 'numpy.ndarray'>
shape of 2d: (2, 4)
8
2
float64


In [36]:
print(np.ones((5,5),dtype=int))
print(np.zeros((4,4),dtype=int))

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [39]:
print(np.full((2,3),100))

[[100 100 100]
 [100 100 100]]
