In [6]:
import numpy as np
# random floats between zero to one(1,0)
arr=np.random.rand(10)
arr

array([0.45855208, 0.53432155, 0.11443164, 0.73211977, 0.11453502,
       0.12330778, 0.04750805, 0.92421525, 0.01494354, 0.21256973])

In [7]:
arr=np.random.rand(3,4)
arr

array([[0.76702988, 0.14628082, 0.76541021, 0.39768146],
       [0.05061848, 0.41031733, 0.94398467, 0.76434758],
       [0.84452536, 0.28954417, 0.09965522, 0.40141553]])

In [9]:
arr=np.random.randn(2,3)#---->random float from standard normal distribution
arr

array([[-1.97960316,  1.2618251 , -2.00428442],
       [ 0.81314449, -0.63349659,  0.30404195]])

In [10]:
arr=np.random.randint(10,100,size=(2,3))#----> start,stop, dimension/number ----->random integer
arr

array([[84, 24, 34],
       [51, 32, 68]])