NUMPY DATA TYPE AND TYPE CASTING

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,34,4])
arr

array([ 1,  2, 34,  4])

In [3]:
arr=np.array([1.2,33,4,55])
arr

array([ 1.2, 33. ,  4. , 55. ])

In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
lst=["asd",1.2,1,22]
arr=np.array(lst)
arr

array(['asd', '1.2', '1', '22'], dtype='<U32')

In [7]:
arr.dtype

dtype('<U32')

In [12]:
arr=np.array([1.2,23,'33'])
arr.dtype

dtype('<U32')

In [17]:
arr=np.array([1,2,3.4,4.9],dtype=np.int64)
arr

array([1, 2, 3, 4], dtype=int64)

In [18]:
arr.dtype

dtype('int64')

type caseting

In [9]:
#typecasting------>astype()
import numpy as np
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [6]:
arr3=arr.astype(np.float64)
arr3

array([1., 2., 3., 4.])

In [11]:
arr4=arr3.astype(np.int64)
arr4.dtype

dtype('int64')

In [13]:
# type casting errors
arr=np.array(["rame","33",'5.5'])
arr1=arr.astype(np.int64)
arr1

ValueError: invalid literal for int() with base 10: 'rame'

In [17]:
arr=np.array([1,1.2,4])
arr1=arr.astype(np.float64)
arr1

array([1. , 1.2, 4. ])

In [20]:
aar=np.array([[1,2,3,4],[3,2,4,5]])
print(aar,aar.ndim)

[[1 2 3 4]
 [3 2 4 5]] 2


In [21]:
aar.shape

(2, 4)

In [22]:
aar.size

8

In [23]:
aar.itemsize

4