In [1]:
import numpy as np 
a=np.arange(1,30)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
b=np.arange(1,30,3)#start,stop,step
b

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [5]:
# linsapce()-> it's give even space between two numbers

b=np.linspace(0,3,3)#start, stop , numer of values
print(b)

[0.  1.5 3. ]


In [20]:
arr=np.logspace(1,4,4) #np.logspace(start,endind ->powers,numper of values)
arr

array([   10.,   100.,  1000., 10000.])

In [4]:
import numpy as np
b=np.arange(0,10,2)
b

array([0, 2, 4, 6, 8])

In [21]:
# np.zeros -> array full of zeros
arr=np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [36]:
arr1=np.zeros([3,4])#rows,columns
arr1


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
arr=np.ones([3,4],dtype=int)
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [38]:
arr=np.ones([2,3])#default float
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [39]:
arr=np.full(10,3)# ----> create an array full of any value
arr

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [43]:
arr=np.full([4,5],10,dtype=float)#([rows,values],default values,dtype=data type)
arr

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [44]:
emp=np.empty([3,4])# uninitialized array--->create an array without setting any values
emp

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])