In [1]:
import numpy as np 
a=np.arange(1,30)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
b=np.arange(1,30,3)#start,stop,step
b

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [5]:
# linsapce()-> it's give even space between two numbers

b=np.linspace(0,3,3)#start, stop , numer of values
print(b)

[0.  1.5 3. ]


In [20]:
arr=np.logspace(1,4,4) #np.logspace(start,endind ->powers,numper of values)
arr

array([   10.,   100.,  1000., 10000.])

In [4]:
import numpy as np
b=np.arange(0,10,2)
b

array([0, 2, 4, 6, 8])