In [4]:
import numpy as np
arr=np.array([1,4,16,32,64])


In [5]:
print(np.sqrt(arr))

[1.         2.         4.         5.65685425 8.        ]


In [6]:
#exponentioal -->np.exp ===>e^x --->x is any integer
a=np.array([1,2,3])
print(np.exp(a))


[ 2.71828183  7.3890561  20.08553692]


In [8]:
# sine function --->np.sin
angle=np.array([0,np.pi/2,np.pi])
print(np.sin(angle))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [4]:
# indexcing and slicng
a=[1,2,3,4,5,6,7,8,9]
print(a[-1])
print(a[-3:-1])

9
[7, 8]


In [12]:
print(a[0:5:1])
print(a[0:9:4])

[1, 2, 3, 4, 5]
[1, 5, 9]


In [13]:
print(a[::2])

[1, 3, 5, 7, 9]


In [19]:
import numpy as np
arr=np.array([10,20,30,40,50,60,70])
arr[0::2]

array([10, 30, 50, 70])